name: lint-scripts

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "15 4 * * 0"

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.32
    steps:
      - uses: actions/checkout@master
      - name: Build and test with coverage
        run: auto-build-and-test-dist
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@master
        with:
          name: build_dir
          path: build_dir
